field: 950c0af3-396d-40b2-a1ca-bd4f80e037b6 # Timeline
fieldLayouts:
  49bcb63d-cf11-4968-a29e-305441b9bdd6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 13c1314c-8e18-452c-99b9-40ddcf9ba5f2 # Year
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 612b5ac8-6133-4b3c-a394-2568feb47f7c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8bf7e76a-4365-4da0-a4c8-a545c79488c3 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16725866-f873-4584-96d7-d0f469563c3f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b6909423-4a75-4b31-8af2-4ec0935f6bcb # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcc0bfcb-aec6-434e-985d-bd3e7940bb36
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c7e7503-494c-4a2c-84c8-fbfb56dcbe67 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d875e246-12cc-48bd-8674-d0fab8d9587b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c4c8063-ca7a-411d-ab4e-cb9498df24c8 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d52de4f-f836-40c8-95df-b2b092845b86
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5f90846-e207-4034-ac8f-ae2a1d0f9186 # Print Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa8115bc-d879-4c08-a194-e28db217ca28
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9d3883d3-f157-4a96-a03e-5b86dbac381d # Print Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a599d19-503a-4f42-8df2-56f837f30934
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 8c06c300-2013-4023-a861-b4409fb0e673
        userCondition: null
fields:
  6c7e7503-494c-4a2c-84c8-fbfb56dcbe67: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: nodeImage
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:48772033-da04-47e7-ad3b-4d3905ac7a65' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:48772033-da04-47e7-ad3b-4d3905ac7a65' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8bf7e76a-4365-4da0-a4c8-a545c79488c3: # Label
    columnSuffix: jywwqrac
    contentColumnType: text
    fieldGroup: null
    handle: nodeLabel
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9c4c8063-ca7a-411d-ab4e-cb9498df24c8: # Description
    columnSuffix: hdedlpoh
    contentColumnType: text
    fieldGroup: null
    handle: nodeDescription
    instructions: null
    name: Description
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      ckeConfig: 3a27561f-43cc-469a-a2fa-6920676a2b3a # Timeline Minimal
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  9d3883d3-f157-4a96-a03e-5b86dbac381d: # Print Link
    columnSuffix: axnafpsw
    contentColumnType: string(255)
    fieldGroup: null
    handle: nodePrintLink
    instructions: null
    name: 'Print Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  13c1314c-8e18-452c-99b9-40ddcf9ba5f2: # Year
    columnSuffix: xcygfokz
    contentColumnType: integer(10)
    fieldGroup: null
    handle: nodeYear
    instructions: null
    name: Year
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 1923
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  a5f90846-e207-4034-ac8f-ae2a1d0f9186: # Print Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: nodePrintImage
    instructions: null
    name: 'Print Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:48772033-da04-47e7-ad3b-4d3905ac7a65' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:48772033-da04-47e7-ad3b-4d3905ac7a65' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b6909423-4a75-4b31-8af2-4ec0935f6bcb: # Title
    columnSuffix: yurhecdi
    contentColumnType: text
    fieldGroup: null
    handle: nodeTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: nodeRegular
name: Regular
sortOrder: 1
