field: cb91d72b-d6d9-439e-8e7b-f3f871694967 # Contributors
fieldLayouts:
  dac15720-7b49-4057-a85d-e128b911703e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 37773290-a8f4-4562-bc4f-fb8c41a63584 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07c2a406-3d54-4ca4-888e-99b42889e52a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92be950a-0880-49a1-bd9a-dcfdb0745a8a # Contribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1e2d30b-a046-4f11-b1c0-877d1dfeaf54
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fcb5a079-6051-4d2f-8a98-fd0c7d162112
        userCondition: null
fields:
  92be950a-0880-49a1-bd9a-dcfdb0745a8a: # Contribution
    columnSuffix: flerxjeq
    contentColumnType: text
    fieldGroup: null
    handle: contribution
    instructions: null
    name: Contribution
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  37773290-a8f4-4562-bc4f-fb8c41a63584: # Label
    columnSuffix: kifzlerj
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: other
name: Other
sortOrder: 2
