field: cb91d72b-d6d9-439e-8e7b-f3f871694967 # Contributors
fieldLayouts:
  2cc04b72-bbd9-4c62-bffc-5f982174c0f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 274b5d00-df3a-4b76-861b-ca591e2af249 # User
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fc89327-b4dd-432c-bbcb-8cea0826756f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a46d69bc-dad9-44b6-9ca0-9ce75f501b7b # Contribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c9c55be-9130-43f2-ae2e-ef2f0422289e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: babe03a7-c77f-44d6-b6f0-ced845b55aa9
        userCondition: null
fields:
  274b5d00-df3a-4b76-861b-ca591e2af249: # User
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: user
    instructions: null
    name: User
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\User
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\users\UserCondition
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Users
  a46d69bc-dad9-44b6-9ca0-9ce75f501b7b: # Contribution
    columnSuffix: qeqfmiox
    contentColumnType: text
    fieldGroup: null
    handle: contribution
    instructions: null
    name: Contribution
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: user
name: User
sortOrder: 1
