fieldLayouts:
  a37e5822-eedc-41a8-abc8-c1e81e11423d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e1c3004c-5dc8-44e9-b898-f9399d75456a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: caec063b-c904-460c-9cea-06d5d524f59c # Events
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4b176d3-bd25-40bd-a856-054c012b7728
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c7724c2-2afd-46bb-92e2-9a3cbffc7b9c
        userCondition: null
handle: anniversaryEvents
hasTitleField: true
name: 'Anniversary: Events'
section: 727301f0-9809-4e7d-88e1-651765c5cfbc # Anniversary: Events
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
