fieldLayouts:
  43afb4bf-4c84-4db2-8014-42abd79351c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 00784f79-d8bd-4125-ab0d-dbb93b37b451
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15dca033-1e00-43b6-bcd3-05ca3c07b14f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6747b933-38e8-4068-8554-89d180569bae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e85c514-8a85-45c7-996a-0824ef8d667b # Description
            instructions: null
            label: Introduction
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6cf69ba-ae80-4cad-8aa3-5192f087ed8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d4265aa-68d0-414f-b465-3b1cdc6ad878 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d2f6ebd-6592-449e-9592-c514cb9f4bc7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e928f3c4-97fc-4ee1-8edd-e0d4c7a53688
            userCondition: null
          -
            elementCondition: null
            fieldUid: 950c0af3-396d-40b2-a1ca-bd4f80e037b6 # Timeline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7acdc4b5-b800-414a-a8f7-086fac7a4cf4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dede4f61-edee-4843-8ef1-048ddb2c9016
        userCondition: null
handle: anniversaryTimeline
hasTitleField: true
name: 'Anniversary: Timeline'
section: d64265d4-5a86-41a5-a68e-c73f8c90123e # Anniversary: Timeline
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
