color: null
fieldLayouts:
  7bc0104f-544f-45b4-810b-2938b10ed8b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9d67c543-135b-4cdb-a0d4-5ce5b0a97dfa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8e13236-f1d0-4327-a58e-8a5ab4493c32 # Contributor - Firstname
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45aa1b17-e32c-4a3c-a263-ae6567a288e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fd78a25-b16e-4d38-a0cc-80c28df2b958 # Contributor - Lastname
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab543ab1-be88-4707-999c-b36587c85fc1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ec318b35-5397-4249-a30a-e398e9d5d029
        userCondition: null
handle: contributor
hasTitleField: false
icon: null
name: Contributor
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{contributorFirstname} {contributorLastname}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
