color: null
fieldLayouts:
  2f2597b8-c11a-4e9c-966b-406e2c7f0662:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 795849cd-759e-4b9f-a635-d38ef3effa54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 21e4a371-781d-4752-b0cd-106498851db5 # Content Image - Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 866b0b7b-e6c2-49e7-acad-63eba46f60c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f854dd38-7b4e-4c96-94ae-741cf4593a1e # Content Image - Size
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c00b8f40-e23d-4a22-9f0e-0544215e4f7d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba470077-c50d-4b28-810e-bc84e953470b
        userCondition: null
handle: contentImage
hasTitleField: false
icon: image
name: 'Content Image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{contentImageImage.one()}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
