color: null
fieldLayouts:
  6bf19c47-529b-409f-9459-24aa3459085c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9507105e-7340-4a96-b242-ba9b1e640a18
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e969c43-23fb-4bfc-a51a-e8e26b1b66ba # Content File - File
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d1f118b-fd00-4700-914e-21a4bef3051b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c7371210-a30f-49a5-a49a-22f4f0a5988f
        userCondition: null
handle: contentFile
hasTitleField: false
icon: file
name: 'Content File'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{contentFileFile.one()}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
