color: null
fieldLayouts:
  7da6fd3a-94c3-478f-a674-fab5f634e07d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 45f8167e-d391-4d56-b476-cd90e0cdabe9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d2d5d09-2278-47d1-8e63-1b70ad5116b4 # Content Gallery - Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15afb77a-b025-40a3-bff2-41c52bc5555b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7613751e-72da-4d7e-ab9e-7a2e5502883d
        userCondition: null
handle: contentGallery
hasTitleField: false
icon: null
name: 'Content Gallery'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
