fieldLayouts:
  fefbb581-3eb0-4105-8e02-4eeeb25ff526:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6b977a03-1507-4076-b345-5af52386bb5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6cdd6eb7-76e7-4ae1-949a-513b1ede029c # Number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0d84512-c795-4d5e-a155-49f14adcc29c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f4cde807-f639-4b1d-bebe-8aa3cd4de160 # Year
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a38f6db-7baa-4c66-b21b-46268af7ea8f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 2a99dd75-c432-4a22-ae67-c3f260158d6c
            userCondition: null
          -
            elementCondition: null
            fieldUid: ff39e44a-c59b-40f1-9eae-5080bf251c2d # Cover
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4fc0de3-6b2e-44ca-85f5-5b57a3e3c551
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e173ad9a-9850-43b4-a574-1029011919ef # File
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fc1b436-4193-45e5-a219-f02a86df7f1f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 17ce3466-62fd-4cc9-b878-6c8ee5449519
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8b097a87-a2ec-4270-8431-a0e733b3fdb3 # Articles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25a0bebb-290b-4c9f-b076-5efb53f7d68d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3e39f094-1b12-4ca3-be29-2091251f7e62
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 09f3e7d3-dd38-4d06-ac5c-fbff3a017d92 # Issues
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
