color: null
fieldLayouts:
  a9096378-ccb8-4131-bb4d-2cf9c6f16615:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 58e9b8bf-8908-4eab-ab0c-3a6b7a4d7838
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae3e2976-5a2f-441c-a712-71c849fe2a40 # Issue Section - Articles
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b075b3a-7acb-4805-a8d8-a2cfcb296bc3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc617b81-152e-4341-b008-7f8b7de6f0a4
        userCondition: null
handle: issueSection
hasTitleField: true
icon: table-list
name: 'Issue Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
