color: null
fieldLayouts:
  a9e15408-a77a-45c2-8483-59eb94987ade:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 317c3e73-709f-45a6-8302-5d2b2fae9c9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 683cb842-2907-43f6-a6be-a4a3833c5eb5 # Timeline Event (Article) - Year
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eacda5ea-3957-4b93-85e3-a1622b3a1b1a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f2f5a7ef-3fd4-4df1-bbd6-d2969e85c127 # Timeline Event (Article) - Label
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cb24d1c-617b-42f6-a106-01805acd6261
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6aee99fe-72b2-4d7d-a791-a8b6b15b3118 # Timeline Event (Article) - Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 295d0f07-cc98-4a1e-9346-b44049b47f30
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b231772f-f289-459a-98aa-4307862a26f1 # Timeline Event (Article) - Publication
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: feaa9774-73b3-449f-80ad-d924f84d4a44
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c68bef4-fce4-4168-aa13-3ca1947567fb # Timeline Event (Article) - Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9703d91-4b69-4773-8abd-193116e73726
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c529f035-1e02-4af8-a7f0-afe4e24e634c # Timeline Event (Article) - Byline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb9edcf0-b7a5-49d1-9b82-c4487889e212
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ee4a9c1-5b55-4094-bd47-fb1c7c2ec826 # Timeline Event (Article) - Lead
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57422757-be01-4bc8-905f-08b22acee68c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fc13160-607f-43ed-9ae7-e5b572317317 # Timeline Event (Article) - Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46eccbcb-62fa-4973-9745-17dc3505b238
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d0000bc8-9493-4559-bc28-18b88f5a9ba3
        userCondition: null
handle: timelineEventArticle
hasTitleField: false
icon: null
name: 'Timeline Event (Article)'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
