headingLevels: false
name: 'Content Note - Content'
options:
  list:
    multiBlock: false
    properties:
      styles: false
toolbar:
  - bulletedList
  - numberedList
  - '|'
  - bold
  - italic
  - link
