headingLevels:
  - 3
name: 'Article - Content'
options:
  list:
    multiBlock: false
    properties:
      styles: false
toolbar:
  - createEntry
  - heading
  - bulletedList
  - numberedList
  - '|'
  - bold
  - italic
  - link
  - removeFormat
