defaultPlacement: end
fieldLayouts:
  b7a32c78-cd72-49e4-bbb9-01bd133eb31c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: bb66b291-f4ad-461e-9754-6a9344810932
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 8438315a-295d-4a8e-b155-3651e4a3eb31
            userCondition: null
            warning: null
        name: Node
        uid: c9da141d-5279-4620-b896-e7c65044a12a
        userCondition: null
handle: anniversary
instructions: ''
maxNodes: null
name: Anniversary
permissions:
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions:
      - singles
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: ''
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabled: true
sortOrder: 2
structure:
  maxLevels: 2
  uid: a5abd382-7a17-4ce4-817d-6b7eb8d53515
