tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: afb6c2da-6684-4057-9dd7-efb701f99159 # Description
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 522d2749-4727-4602-969b-fb67f8bb3518
        userCondition: null
        warning: null
        width: 100
    name: Profile
    uid: 750a39ce-dd7c-4d2f-b5b4-2b7d461cb87e
    userCondition: null
