fieldLayouts:
  abf7eb01-2310-49a9-ae06-3a759b7a8b6f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d924566c-6ec2-44b2-8697-07b4ce93d5d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef819456-45fb-4c34-a4e6-e32ab105c6a3 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ceaba65-1014-4ff8-a2a3-ece91015c744
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb91d72b-d6d9-439e-8e7b-f3f871694967 # Contributors
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb839516-3d70-4c01-aa41-435479339d30
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f841490a-2049-412c-86f3-398f92b940fb
        userCondition: null
fs: embeds
handle: embeds
name: Embeds
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
