altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  cca57829-6e74-4dc0-83ef-0ee9f040436a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9f9537df-af48-428d-af7d-285c16c0a6bf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5f75ceca-1919-47c4-834d-1259c2db466d
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
