columnSuffix: lmealsfp
contentColumnType: string(255)
handle: adLink
instructions: null
name: Link
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
