columnSuffix: null
contentColumnType: string
fieldGroup: 3d811369-1bfd-4b73-a933-fa5cf4ae0a6a # Anniversary
handle: anniversaryEvents
instructions: null
name: Events
searchable: false
settings:
  contentTable: '{{%matrixcontent_anniversaryevents}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
