columnSuffix: lzeedpap
handle: articleAd
instructions: null
name: 'Article Ad'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
