columnSuffix: mfgqsbwu
contentColumnType: text
handle: contentContent
instructions: null
name: Content
searchable: true
settings:
  embedVolumes:
    - 9549d5ad-d6e4-45a6-8376-edfc95d27e18 # Embeds
  fileVolumes:
    - 5fa65803-cc01-4718-967f-17c1fac740ab # Files
  imageVolumes:
    - 48772033-da04-47e7-ad3b-4d3905ac7a65 # Images
  templates:
    -
      __assoc__:
        -
          - node
          - quote
        -
          - template
          - _editor/quote.twig
    -
      __assoc__:
        -
          - node
          - note
        -
          - template
          - _editor/note.twig
    -
      __assoc__:
        -
          - node
          - image
        -
          - template
          - _editor/image.twig
    -
      __assoc__:
        -
          - node
          - gallery
        -
          - template
          - _editor/gallery.twig
    -
      __assoc__:
        -
          - node
          - embed
        -
          - template
          - _editor/embed.twig
    -
      __assoc__:
        -
          - node
          - file
        -
          - template
          - _editor/file.twig
translationKeyFormat: null
translationMethod: none
type: editor\fields\Editor
