columnSuffix: null
handle: contentNoteContent
instructions: null
name: 'Content Note - Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 30ad3ecb-e175-42bd-8a93-6b5432ae932f # Content Note - Content
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
