columnSuffix: null
contentColumnType: string
handle: contributors
instructions: null
name: Contributors
searchable: true
settings:
  entryTypes:
    - 36ea09ec-8867-4d74-96ee-d55c21e44104
    - a3b06153-7a2e-425b-a7f7-61e925da17b9
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
