columnSuffix: heaktlji
handle: contentImagePosition
instructions: null
name: 'Shared - Image Position'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - top
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - bottom
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
