columnSuffix: null
handle: homeSectionLayouts
instructions: null
name: 'Home Section - Layouts'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 10492ed9-cbb8-423a-951b-8e0dd55b11f4 # Home Section Layout
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
