columnSuffix: null
handle: homeSections
instructions: null
name: 'Home - Sections'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - d0ba75f4-0ec9-406b-8e28-5a50980147cc # Home Section
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
