columnSuffix: null
contentColumnType: string
handle: homeBlocks
instructions: null
name: Blocks
searchable: false
settings:
  entryTypes:
    - 6a4b325d-b443-4b35-85ed-bd5b9d092f11
    - d0ba75f4-0ec9-406b-8e28-5a50980147cc
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
