columnSuffix: null
handle: issueSections
instructions: null
name: 'Issue - Sections'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - b2237231-890f-4253-ab7f-251f41d3598c # Issue Section
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
