columnSuffix: null
contentColumnType: string
handle: issueArticles
instructions: null
name: Articles
searchable: true
settings:
  entryTypes:
    - b2237231-890f-4253-ab7f-251f41d3598c # Group
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
