columnSuffix: tcuhufco
contentColumnType: integer(10)
handle: issueNumber
instructions: null
name: Number
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
