columnSuffix: hdiprzew
handle: issueSectionTitle
instructions: null
name: 'Legacy - Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 32
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
