columnSuffix: tcuhufco
contentColumnType: integer(10)
fieldGroup: c02d5119-8f14-4b30-acf1-29e22375aef5 # Issue
handle: issueNumber
instructions: null
name: Number
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
