columnSuffix: xcygfokz
handle: nodeYear
instructions: null
name: 'Timeline - Regular - Year'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1923
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
