columnSuffix: null
handle: subscriptionEmail
instructions: null
name: 'Subscription - Email'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
