columnSuffix: ziprywbg
handle: subscriptionEndDate
instructions: null
name: 'Legacy - End Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
