columnSuffix: ivoorgte
handle: timelineEventArticleDescription
instructions: null
name: 'Legacy - Description'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: c7ddc58d-ce45-4fdd-a7b2-d1318ae1afb1 # Timeline Event - Description
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
