columnSuffix: null
contentColumnType: string
fieldGroup: 3d811369-1bfd-4b73-a933-fa5cf4ae0a6a # Timeline
handle: timelineNodes
instructions: null
name: Timeline
searchable: false
settings:
  contentTable: '{{%matrixcontent_timelinenodes}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
