changedFieldIndicator: 691610109
field: 3458cf19-d496-4a9e-808d-47e0b2323224 # Layouts
fieldLayouts:
  23ab6e66-b5e4-4bc2-8ca4-96798abadd88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0cf2962b-f593-4e6b-9ac2-9544710d8aad # Appearance
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0e6e01f-d9fd-41ff-983f-5dfc4bc9cadb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f197e112-2648-4604-852c-cf4171abc6c2 # Articles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33bed828-5224-4d4d-a75d-f3c631cc7cfa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df3cc6e8-563a-4d60-a438-420c7a256ce2
        userCondition: null
fields:
  0cf2962b-f593-4e6b-9ac2-9544710d8aad: # Appearance
    columnSuffix: yslapbix
    contentColumnType: string
    fieldGroup: null
    handle: appearance
    instructions: null
    name: Appearance
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Medium: Vertical, Vertical'
            -
              - value
              - vv
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Medium: Vertical, Horizontal'
            -
              - value
              - vh
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Medium: Horizontal, Horizontal'
            -
              - value
              - hh
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Large: Vertical'
            -
              - value
              - v
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Large: Horizontal'
            -
              - value
              - h
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f197e112-2648-4604-852c-cf4171abc6c2: # Articles
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: articles
    instructions: null
    name: Articles
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources:
        - 'section:7dac239d-784f-4ec9-80fc-46b2c4362060' # Articles
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
