defaultPlacement: end
enableVersioning: false
entryTypes:
  - 3cc8b7a7-5c00-4889-b691-ca2edc74df61 # Default
handle: ads
name: Ads
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
