defaultPlacement: end
enableVersioning: false
handle: anniversaryBook
name: 'Anniversary: Book'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/anniversary/book.twig
    uriFormat: 100/buch
type: single
