defaultPlacement: end
enableVersioning: true
entryTypes:
  - 437bb34b-df33-490d-a865-5fcd8eac751b # Contributor
handle: contributors
maxAuthors: 1
name: Contributors
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/user.twig
    uriFormat: 'autor-innen/{slug}'
type: channel
