defaultPlacement: end
enableVersioning: true
entryTypes:
  - 241d2e87-c08f-4847-90e8-4ad1d718f876 # Format
handle: formats
maxAuthors: 1
name: Formats
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/format.twig
    uriFormat: 'rubriken/{slug}'
type: channel
