defaultPlacement: end
enableVersioning: false
entryTypes:
  - 18ae8f32-e01d-480d-b9b7-9b166fcdceda # Home
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/home.twig
    uriFormat: __home__
type: single
