defaultPlacement: end
enableVersioning: true
entryTypes:
  - b2c997ba-ecc0-418e-86a8-20c5afd7e1d6 # Page
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/page.twig
    uriFormat: '{slug}'
type: channel
