defaultPlacement: end
enableVersioning: false
entryTypes:
  - bd3e37bc-785f-4f35-a3ba-42a801ec0e80 # Timeline
handle: timeline
name: Timeline
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/timeline.twig
    uriFormat: '100'
type: single
