defaultPlacement: end
enableVersioning: true
entryTypes:
  - 785ebd4b-4b47-46f7-a0a2-cd889b31058e # Topic
handle: topics
maxAuthors: 1
name: Topics
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # Zürcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/topic.twig
    uriFormat: 'themen/{slug}'
type: channel
